name: Corosync QNetd
version: dev
slug: corosync_qnetd
description: Corosync Quorum Network Daemon for Proxmox Quorum
url: https://github.com/modelrockettier/corosync-qnetd
arch:
  - aarch64
  - amd64
init: false
startup: services
host_network: true
map:
  - addon_config:rw
ports:
  5403/tcp: 5403
ports_description:
  5403/tcp: Corosync QNetd port
