name: Corosync QNetD
version: "latest"
slug: corosync-qnetd
description: Docker container for Proxmox Corosync QNet Daemon
url: "https://github.com/modelrockettier/docker-corosync-qnetd"
startup: services
init: false
arch:
  - aarch64
host_network: true
map:
  - config:rw
options:
  qnetd_data: /etc/corosync
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  qnetd_data: str
ports:
  5403/tcp: 5403
image: modelrockettier/corosync-qnetd:arm64v8
