name: Corosync QNetD
version: "latest"  # or specific version if available
slug: corosync-qnetd
description: "Docker container for Proxmox Corosync QNet Daemon"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: "https://github.com/modelrockettier/docker-corosync-qnetd"
init: false
ports:
  5403/tcp: 5403
options:
  qnetd_data: /etc/corosync
schema:
  qnetd_data: str
