name: Corosync QNetd
version: dev
slug: corosync_qnetd
description: Corosync Quorum Network Daemon for Home Assistant
url: https://github.com/modelrockettier/corosync-qnetd
arch:
  - aarch64
  - amd64
init: false
startup: services
map:
  - ssl
  - share:rw
ports:
  5403/tcp: 5403
ports_description:
  5403/tcp: QNetd service port
user: "903"
group: "903"
volumes:
  etc_corosync: /etc/corosync
