name: "Corosync QNetd"
version: "1.0.0"
slug: "corosync_qnetd"
description: "Corosync Quorum Network Daemon for Home Assistant"
url: "https://github.com/modelrockettier/corosync-qnetd"
arch:
  - aarch64
startup: services
boot: auto
init: false
ports:
  5403/tcp: 5403
schema:
  port: "int?"
ports_description:
  5403/tcp: "QNetd service port"
options:
  port: 5403
